### ISSUE TITLE
Compatibility issue in DataTable 2.0.0

### ISSUE THREAD

**Issue by tufail-cedcommerce** [dhobi/datatables.colResize#26]
Hi @dhobi, @jstark518, @jqnatividad, @Javaman1138 and @hchiam, could you please upgrade this plugin so it can work with DataTable 2.0.0 too?

Thank you.

**Comment by rahul-katikineni** [comment]
I have been able to make minor modifications for it to work with 2.0
Please have a look and see if it helps.

[jquery.dataTables.colResize.txt](https://github.com/dhobi/datatables.colResize/files/14740873/jquery.dataTables.colResize.txt)

**Comment by tufail-cedcommerce** [comment]
> I have been able to make minor modifications for it to work with 2.0 Please have a look and see if it helps.
> 
> [jquery.dataTables.colResize.txt](https://github.com/dhobi/datatables.colResize/files/14740873/jquery.dataTables.colResize.txt)

First of all thanks for the modification.

I've tried using it but it is only resizing first two rows. I need it to resize the complete column. I'm using Server-side processing(AJAX) for populating the data.

My table looks like this.
![image](https://github.com/dhobi/datatables.colResize/assets/87505536/f0c2ccb3-2aec-4419-bc38-de01d03e1a24)

Could you please help here @rahul-katikineni.

**Comment by gpientka** [comment]
Getting an error

Uncaught TypeError: this.s.dt.oInstance.api.columns is not a function
    at jquery.dataTables.colResize_new.js:362:37
    at Array.map (<anonymous>)
    at ColResize._fnGetAllColumns (jquery.dataTables.colResize_new.js:359:22)
    at HTMLDocument.<anonymous> (jquery.dataTables.colResize_new.js:276:14)
    at HTMLDocument.dispatch (jquery.min.js:2:41772)
    at y.handle (jquery.min.js:2:39791)

Any help would be appreciated @rahul-katikineni

**Comment by mvksages** [comment]
Do we have any updates on this ? This is very helpful if it works with latest DataTable. Great feature by the way.

**Comment by fdaugan** [comment]
I cannot create a MR based on @rahul-katikineni work because there are too much changes.

However, after few changes changes I got the desired behavior.

Merged file: [jquery.dataTables.colResize.js](https://raw.githubusercontent.com/fdaugan/datatables.colResize/refs/heads/master/jquery.dataTables.colResize.js)

Changes:
```js
    _fnApplyWidthColumn: function (column, width) {
++    [$(column.nTh.table().context[0].colgroup).find('col')[column.idx], $(column.nTh).closest('table').find('colgroup col')[column.idx]].filter(a => a).forEach(a => a.style = `width:${width}px`);
      $(column.nTh).outerWidth(width + "px");
      column.sWidth = width + "px";
    }
```

Configuration:
```json
colResize: {
      onResize: function (column) {
        const $wrapper = $table.closest('.dt-layout-table');
        const targetWidth = $wrapper.find('.dt-scroll-headInner').width();
        $wrapper.find('table').width(targetWidth).css('max-width', `${targetWidth}px`);
      },
    },
```

Behavior:
![Oct-08-2024 00-13-58](https://github.com/user-attachments/assets/fae1fd3a-e6ad-443b-9360-912a66c329ee)

**Comment by dhobi** [comment]
Version 2.0.0 of datatables.net-colresize-unofficial has just been release just released. Give it a try.
